Repository fga-eps-mds/2020.1-GaiaDex-BackEnd, pull requests merged in 2020-09, with the labels that each got.

#3 Start Backend Project
  package-lock.json
  package.json
  src/index.js
  src/routes/index.js
Labels: enhancement

#4 Dockerize environment
  Dockerfile
  docker-compose.yml
Labels: enhancement

#14 US05, US10 and US11, create, edit and delete user
  package.json
  src/index.js
  src/models/user.js
  src/routes/authRoutes.js
  src/schemas/userSchema.js
Labels: enhancement, mds

#19 I11 visualizar informacoes sobre a planta
  .gitignore
  package-lock.json
  package.json
  src/config/index.js
  src/index.js
  src/models/Comment.js
  src/models/Plant.js
  src/models/Topico.js
  src/routes/commentRoutes.js
  src/routes/plantRoutes.js
  src/routes/topicRoutes.js
  yarn.lock
Labels: backend, mds
