Repository fga-eps-mds/2020.1-GaiaDex-BackEnd, pull requests merged in 2020-12, with the labels that each got.

#123 Modificar funcionamento do like
  .dockerignore
  src/models/Comment.js
  src/models/Likes.js
  src/models/Topic.js
  src/routes/auth.js
  src/routes/commentRoutes.js
  src/routes/topicRoutes.js
Labels: In Progress, backend, bug, mds

#128 Workflow on github actions
  .github/workflows/ci.yml
  .github/workflows/homologDeploy.yml
  .github/workflows/productionDeploy.yml
  homolog-docker-compose.yml
  homologDataBaseDockerfile
  homologDockerfile
  package.json
  productionDockerfile
  src/index.js
Labels: In Progress, backend, enhancement, eps

#136 I134 arrumar branch 130 na nova arquitetura
  src/controller/AuthController.js
  src/controller/CommentController.js
  src/controller/FavoritesController.js
  src/controller/MyPlantsController.js
  src/controller/PlantController.js
  src/controller/TopicController.js
  src/models/Plant.js
  src/models/User.js
  src/planta.jpg
  src/routes/authRoutes.js
  src/routes/commentRoutes.js
  src/routes/favoriteRoutes.js
  src/routes/myPlantRoutes.js
  src/routes/plantRoutes.js
  src/routes/topicRoutes.js
  src/schemas/userSchema.js
Labels: backend, mds
